services:
  nginx:
    image: sumnic82/rodnaya-nginx:${IMAGE_TAG}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - app_net

  server:
    image: sumnic82/rodnaya-server:${IMAGE_TAG}
    env_file:
      - ./server/.env.prod
    volumes:
      - ./server/static:/app/static
    # command: yarn migrate && yarn start:prod
    networks:
      - app_net

  postgres:
    image: postgres:15
    env_file:
      - ./server/.env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_net

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/ccertbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: >
      /bin/sh -c 'while :; do certbot renew; sleep 12h; done'
    networks:
      - app_net
    restart: unless-stopped

networks:
  app_net:
volumes:
  pgdata:
