services:
  nginx:
    image: sumnic82/rodnaya-nginx:${IMAGE_TAG}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - app_net
      - ry_net

  server:
    image: sumnic82/rodnaya-server:${IMAGE_TAG}
    env_file:
      - ./server/.env.prod
    volumes:
      - ./server/static:/app/static
    # command: yarn migrate && yarn start:prod
    networks:
      - app_net

  postgres:
    image: postgres:15
    env_file:
      - ./server/.env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_net

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: /bin/sh
    command:
      - -c
      - "while true; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done"
    networks:
      - app_net
    restart: unless-stopped

  migrate:
    image: sumnic82/rodnaya-server:${IMAGE_TAG}
    command: yarn migrate:prod
    depends_on:
      - postgres


networks:
  app_net:
  ry_net:
    external: true
volumes:
  pgdata:
